spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: BASIC

endpoint:
  no-auth: > 
    /swagger-ui*/**,
    /favicon.ico,
    /v3/api-docs*/**,
    /actuator*/**